/*
Exercise -26 (Compare Two Random Numbers )
Raj is creating a program as part of a game application in which he needs to compare a random number which is generated by the game with the random number which a player has guessed. Help him to write a program to compare two random numbers. If both match. It should print “The Random numbers were the same” or else should print “The Random Numbers were different “
Solution : Use Random class of UtilPackage to generate random numbers.
Use the nextInt() method of Random class.
 */
package com.techment.logicBuildingProblem;

import java.util.Random;

public class CompareTwoRandomNumbers {

	public static void main(String[] args) {

		Random rand = new Random(); 
		
		int num1 = rand.nextInt(1000); 
        int num2 = rand.nextInt(1000); 
        
        if(num1==num2) {
        	System.out.println("The Random numbers were the same");
        }
        else
        	System.out.println("The Random Numbers were different");
		
	}

}
